# -*- coding: utf-8 -*-
require "colorize"
require 'command_line/global'

task :default do
  system "rake -T"
end

desc "mk knowledge fixer graph" #desc -> description
task :mk_graph do # any name on task_name
  dir = ARGV[1] || '.'
  layer = ARGV[2] || '2'
  ["ruby ./mk_dir_yaml.rb -L #{layer.to_i} #{dir}",
   'ruby ./mk_node_edge.rb',
   'ruby ./mk_semi_lattice.rb'].each do |comm|
    puts comm
    system comm
  end
  exit
end

