# -*- coding: utf-8 -*-
require "colorize"
require 'command_line/global'

task :default do
  system "rake -T"
end

desc "mk knowledge fixer graph" #desc -> description
task :mk_graph do # any name on task_name
  # Usage:
  #   rake mk_graph
  # 
  # Description:
  #   1. ruby codes/mk_dir_array.rb -L 2 .         # カレントディレクトリ以下2階層のディレクトリ構造をdir.yamlに出力
  #   2. ruby codes/mk_node_edge.rb dir.yaml > node_edge.txt  # dir.yamlからノード・エッジ情報をnode_edge.txtに出力
  #   3. ruby codes/knowledge_fixer.rb node_edge.txt          # node_edge.txtを使ってknowledge fixerを実行
  ['ruby codes/mk_dir_array.rb -L 2 .',
   'ruby codes/mk_node_edge.rb dir.yaml > node_edge.txt',
   'ruby codes/knowledge_fixer.rb node_edge.txt'].each do |comm|
    puts comm
    system comm
  end
  exit
end

