#!/usr/bin/env ruby

require 'optparse'
class PasswordGenerator
  def initialize(length=4, symbol: true)
    @length = length
    @symbol = symbol
  end

  def generate
    chars = ('a'..'z').to_a
    chars += ('A'..'Z').to_a
    chars += ('0'..'9').to_a
    chars += %w[! @ # $ % ^ & * ( ) _ + - = [ ] { } ; : , . / ?] if @symbol
    password = Array.new(@length) { chars.sample }.join
    puts password
  end
end

options = { length: 4, symbol: true }

OptionParser.new do |opts|
  opts.banner = "Usage: mk_passwd_optparse [options]"

  opts.on('-d LENGTH', '--digit LENGTH', Integer, 'Password length') do |len|
    options[:length] = len
  end

  opts.on('-S', 'Exclude symbols from password') do
    options[:symbol] = false
  end
end.parse!

PasswordGenerator.new(options[:length], symbol: options[:symbol]).generate
